# Generated by Django 4.0.6 on 2022-08-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_follow_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
