# Generated by Django 4.0.6 on 2022-08-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoption',
            old_name='price',
            new_name='additional_price',
        ),
    ]
