# Generated by Django 4.0.6 on 2022-08-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_price_productoption_additional_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailimage',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='thumbnailimage',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
